name: Unit Testing Code Base

on:
  # Ensuring the main code base works 
  push:
    branches: [ "main" ]
  # Ensuring any pull requests to main are tested 
  pull_request:
    branches: [ "main" ]

jobs:
  # Testing to be run on Linux distros
  build:
    runs-on: ubuntu-latest
    # what versions of the run times need to be tested
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    
    # Getting git code base
    - uses: actions/checkout@v4
    
    # Creating the python environment
    - name: Set up Python Environment ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    # Creating the poetry build system environment
    - name: Build with Poetry
      uses: abatilo/actions-poetry@v3
    - name: Installing Poetrey Dependencies
      run: poetry install

    # Running the tests required
    - name: Running automated poetry Tests
      run: poetry run pytest-cov -v
